# Generated by Django 2.1.4 on 2019-02-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(default='Tehran', max_length=40),
        ),
        migrations.AddField(
            model_name='employee',
            name='description',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='isAlumni',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='major',
            field=models.CharField(default='Computer Engineering', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
