# Generated by Django 2.1.4 on 2019-02-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0002_auto_20190201_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='major',
            field=models.CharField(choices=[('CoE', 'مهندسی کامپیوتر'), ('ElE', 'مهندسی برق'), ('MeE', 'مهندسی مکانیک'), ('MaE', 'مهندسی مواد'), ('ChE', 'مهندسی شیمی'), ('IE', 'مهندسی صنایع'), ('CiE', 'مهندسی عمران')], max_length=50),
        ),
    ]
