# Generated by Django 2.1.4 on 2019-02-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0005_auto_20190201_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Resume',
            field=models.ForeignKey(default=None, null=True, on_delete='SET_NULL', related_name='employee', to='hiring.Resume'),
        ),
    ]
