# Generated by Django 2.1.4 on 2019-02-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0008_auto_20190201_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Resume',
        ),
    ]
