# Generated by Django 2.1.4 on 2019-02-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0013_employee_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Resume',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
