# Generated by Django 2.1.4 on 2019-02-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0014_auto_20190201_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
