# Generated by Django 2.1.4 on 2019-02-01 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0016_employee_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Resume',
            new_name='resume',
        ),
    ]
